[workspace]
authors   = ["ZhengYu, Xu <zen-xu@outlook.com>"]
channels  = ["conda-forge", "https://repo.prefix.dev/cxxlibs"]
name      = "mmap_db"
platforms = ["linux-64"]
version   = "0.1.0"

[tasks]

[dependencies]
python        = ">=3.13,<3.14"
lld           = ">=19.1.7,<21"
clang         = ">=19.1.7,<21"
clangxx       = ">=19.1.7,<21"
clang-tools   = ">=19.1.7,<21"
lldb          = ">=19.1.7,<21"
llvm-tools    = ">=19.1.7,<21"
compiler-rt   = ">=19.1.7,<21"
cmake         = ">=3.31.5,<4"
ninja         = ">=1.12.1,<2"
cmake-format  = ">=0.6.13"
pre-commit    = "*"
taplo         = "*"
benchmark     = ">=1.9.4,<2"
libarrow      = ">=21.0.0,<22"
mimalloc      = ">=3.1.5,<4"
ipython       = ">=9.4.0,<10"
pyarrow       = ">=21.0.0,<22"
pyarrow-stubs = ">=20.0.0.20250716,<21"
pandas        = ">=2.3.2,<3"
libassert     = { version = ">=2,<3", channel = "https://repo.prefix.dev/cxxlibs" }
nanoarrow     = { version = ">=0.6.0,<0.7", channel = "https://repo.prefix.dev/cxxlibs" }
